### ISSUE TITLE
TARGET example in Plugins documentation too short

### ISSUE THREAD

**Issue by scandey** [OpenC3/openc3.com#15]
In the plugins.txt description, the TARGET keyword requires two parameters, but the example given only has one. I suspect the automatic converter from COSMOS4 to openC3 also does not know about the two required parameters, since the results fail to install with missing parameters of the TARGET keyword (separate bug). 

https://openc3.com/docs/v5/plugins

```
Example Usage:

TARGET INST
```
Should be something like

```
Example Usage:

TARGET INST INST
```

**Comment by jmthomas** [comment]
closed by https://github.com/OpenC3/openc3/pull/219
