### ISSUE TITLE
change 'openc3.bat start' to 'openc3.bat run' in installation instructions

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/openc3.com#18]
Hi,

According to issue https://github.com/OpenC3/cosmos/issues/245 it's better to run the provided containers than rebuild them from scratch. , using 'openc3.bat run' instead of  openc3.bat start'.

I would suggest to make a mention of this, or change the instructions at the bottom of page https://openc3.com/docs/v5/installation.

greetings, Jurgen

**Comment by jmthomas** [comment]
closed by #21
