### ISSUE TITLE
Plugins: /public or /data folder: which to use for images?

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/openc3.com#22]
Here: https://github.com/OpenC3/cosmos/tree/main/openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/public/
![image](https://user-images.githubusercontent.com/837194/205639699-9adec4a8-c788-42a9-9ba4-f079338db6b3.png)

... reside some image files, but according to https://openc3.com/docs/v5/plugins#plugin-directory-structure ...
 

<html>
<body>

targets/TARGETNAME/data | Use this folder to store any general data that is needed by the target. For example, any image files would be stored here.
-- | --

</body>
</html>

- which is best for images?
- what is the usage of /public? This is missing from the online documentation.

gr. Jurgen

**Comment by jmthomas** [comment]
@jurgensymynck Thanks, this was not documented correctly. The /data folder is left over from COSMOS 4 but we decided to make a /public folder to better match typical website structures. CANVAS images are explicitly loaded from the /public folder.
