### ISSUE TITLE
References to COSMOS on website

### ISSUE THREAD

**Issue by jeffstjean** [OpenC3/openc3.com#3]
I know you guys are probably pretty busy with the next OpenC3 release coming up but just noticed the homepage to OpenC3 has [a reference to COSMOS](https://github.com/OpenC3/openc3.com/blob/198d7f2b71b37b04e5c5a36c9ce1f86072e81f66/index.html#L114) that I think was missed. Also the training video still has the name COSMOS in the title.

**Comment by jmthomas** [comment]
Yeah we haven't had time to remake the video with OpenC3

**Comment by jmthomas** [comment]
New video of OpenC3 is live!
