### ISSUE TITLE
./compose.yaml is invalid

### ISSUE THREAD

**Issue by AceSimulations** [OpenC3/openc3.com#31]
I have been using cosmos 5 for a while and it runs great. I decided to update to openc3 but after cloning the github and running sudo ./openc3.sh start I recieve the following error.

WARNING: The OPENC3_REGISTRY variable is not set. Defaulting to a blank string.
WARNING: The OPENC3_TAG variable is not set. Defaulting to a blank string.
WARNING: The OPENC3_BUCKET_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The OPENC3_BUCKET_PASSWORD variable is not set. Defaulting to a blank string.
ERROR: The Compose file './compose.yaml' is invalid because:
Unsupported config option for services.openc3-cosmos-cmd-tlm-api: 'group_add'
Unsupported config option for services.openc3-cosmos-init: 'group_add'
Unsupported config option for services.openc3-cosmos-script-runner-api: 'group_add'
Unsupported config option for services.openc3-operator: 'group_add'

I have verified docker and docker-compose are installed and ran docker ps to verify no other docker containers were running. I am not sure what the issue is.

**Comment by ryanmelt** [comment]
group_add requires docker-compose version 1.27+.
Also, you will need to update your .env file, with the one from our current versions.   (It has all the OPENC3_ variables in it).
