### ISSUE TITLE
Tools > Timeline example image appears broken

### ISSUE THREAD

**Issue by MichaelBonnet** [OpenC3/openc3.com#36]
Assuming that the Timeline section is intended to have an example image like other sections, the example image appears broken.

Screenshot on Edge:
![image](https://user-images.githubusercontent.com/36342359/217655869-3e2144a1-4ac7-4596-b7b9-bd14fcfb9915.png)

Screenshot on Firefox:
![image](https://user-images.githubusercontent.com/36342359/217656198-6ec53aaf-c596-4b05-b05a-93aeb231c763.png)

Screenshot on Chrome:
![image](https://user-images.githubusercontent.com/36342359/217656604-e201a65b-153c-4564-8903-3db1bfde1f06.png)

**Comment by jmthomas** [comment]
Tools Timeline was out of date and was updated with Calendar: https://openc3.com/docs/v5/calendar
Links appear to be fixed.
