### ISSUE TITLE
Document PACKET_TIME

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/openc3.com#44]
The old links to blog posts are broken. You have to take the last part of the url and paste it on Ball's Cosmos site to get to them. Maybe those posts should be imported?

- https://openc3.com/docs/v5/protocols#template-protocol in the paragraph there is a link to a blog post
  - https://github.com/OpenC3/openc3.com/blob/website/_docs_v5/2_configuration/protocols.md
- there's also a great blog post about setting packet time. Should that be migrated into the documentation?

**Comment by jmthomas** [comment]
The old blog posts generally aren't going to be pulled over verbatim because they apply exclusively to COSMOS 4. However there is useful information there that we need to add to the current COSMOS 5 documentation including PACKET_TIME.

**Comment by tsjordan-eng** [comment]
@jmthomas , #46 is ready.  Let me know if you want more changes.  I only don't know about the 'stored' flag, but maybe that documentation belongs elsewhere.
